<a href="https://colab.research.google.com/github/Imanita7/AI-for-Science-and-Engineering/blob/main/Student_performance_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Predicting students at risk of poor academic performance using ML
##Project Problem
Students experience academic difficulties without realizing that they're falling behing. This project investigates whether ML can be used to identify students who are at risk of poor academic performance using factors such as previous grades, study time, absences, past failures and other student-related characteristics.

##Intended AI/ML outcome
The intended outcome is to develop a ML classification system that predicts whether a student is at risk of poor academic performance or not. The system will classify students into 2 categories:
    - At risk
    - Not at risk
The goal is to identify potential academic hardships early enough in order to support appropriate academic intervention.

##Data required
The project requires student-related academic and behavioural information. Potentially useful variables include:
  - Previous academic grades
  - Study time
  - Number of absences
  - Number of previous class failures
  - Access to educational support
  - Family educational support
  - Participation in extracurricular activities
  - Internet access
  - Family relationship quality
  - Free time
  - Health status
  - Other demographic and educational factors
  
The target variable will be the student's final academic performance.

In [1]:
!pip install -q ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

#Fetch the student performance dataset
student_performance = fetch_ucirepo(id=320)

#Get the features and targets
x = student_performance.data.features
y = student_performance.data.targets

#Combine them into one dataframe
df = pd.concat([x,y], axis = 1)

#Display the first few rows
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

##Sample of the dataset
The table below shows a small portion of the student performance dataset.

In [4]:
df.head(10)
print("Dataset shape:", df.shape)
df.info()

Dataset shape: (649, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

##Features and target
###Potential input features
The ML model will use factors that may be available before the final academic outcome is known including:
  - Study time
  - Number of previous failures
  - Number of absences
  - Educational support
  - Family support
  - Previous-period grades
  - Internet access
  - Free time
  - Health status
  - School-related and demographic factors

###Target
The target variable will be created from the final grade (e.g G3)
    - G3 < 10 = At risk
    - GE >= 10 = Not at risk
  
Therefore, this is a binary classification problem.

In [5]:
#Create the target variable
df["at_risk"] = (df["G3"] < 10).astype(int)

#Risk variables
df["risk_label"] = df["at_risk"].map({
    0: "Not at risk",
    1: "At risk"
})

#Display the results
df[["G3", "at_risk", "risk_label"]].head(10)

   G3  at_risk   risk_label
0  11        0  Not at risk
1  11        0  Not at risk
2  12        0  Not at risk
3  14        0  Not at risk
4  13        0  Not at risk
5  13        0  Not at risk
6  13        0  Not at risk
7  13        0  Not at risk
8  17        0  Not at risk
9  13        0  Not at risk

G3 is used only to create the target variable and is not used as an input feature.

##Proposed ML workflow
The proposed workflow consists of the following stages:
  1. **Data Collection** - Obtain the student performance dataset.
  2. **Data Cleaning** - Check the data set for missing values, duplicate records and inconsistent data.
  3. **Feature Selection** - Select relevant academic, behavioral and demographic variable.
  4. **Data Processing** - Convert categorical variables into numerical representations so that they can be used by a machine learning model.
  5. **Train/Test split** - Divivde the dataset into training and testing sets.
  6. **Model Training** - Train a classification model using the tarining data.
  7. **Model Evaluation** - Evaluate the model using the testing data and appropriate classification metrics.
  8. **Risk Prediction** - Use the trained model to classify students as either "At risk" or "Not at risk".
  9. **Early Intervention** - The predictions could eventually help identify students who may benefit from additional academic support.

```text
┌─────────────────────────────┐
│  1. Data Collection         │
│  Student Performance data   │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  2. Data Cleaning           │
│  Missing values, duplicates │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  3. Feature Selection       │
│  Academic/behavioural/etc.  │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  4. Data Preprocessing      │
│  Convert categorical data   │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  5. Train/Test Split        │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  6. Model Training          │
│  Classification model       │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  7. Model Evaluation        │
└──────────────┬──────────────┘
               ↓
┌─────────────────────────────┐
│  8. Risk Prediction         │
└──────────────┬──────────────┘
               ↓
          ┌────┴────┐
          ↓         ↓
     ┌─────────┐ ┌─────────────┐
     │At Risk  │ │Not At Risk  │
     └────┬────┘ └──────┬──────┘
          ↓             ↓
 ┌────────────────┐ ┌───────────────┐
 │9. Early        │ │Continue       │
 │Intervention    │ │Monitoring     │
 └────────────────┘ └───────────────┘

In summary, the dataset is first cleaned and prepared for analysis. Relevant features are then selected and categorical data is converted into a suitable format. The data is divided into a training and testing sets, after which a classification model is trained.
The model is evaluated using the testing data. Finally, the model predicts whether a student is at risk of poor academic performance or not. Students identified as being at risk could then receive early academic support.

##Dataset source
Cortez, P. (2008) Student Performance. UCI Machine Learning Repository.
https://doi.org/10.24432/C5TG7T

The dataset contains student academic, demographic, social and school-related information and includes final academic grades.